Repository mopidy/mopidy, pull requests merged in 2023-08, with the labels that each got.

#2102 add "tox -e ci", to test before pushing.
  docs/changelog.rst
  tox.ini
Labels: C-enhancement

#2100 deps.py and ext.py 100% coverage.
  mopidy/ext.py
  tests/internal/test_deps.py
  tests/test_ext.py
Labels: C-enhancement

#2104 Replace pkg_resources with importlib.metadata / import_module.
  docs/changelog.rst
  mopidy/__init__.py
  mopidy/ext.py
  mopidy/internal/deps.py
  setup.cfg
  tests/internal/test_deps.py
  tests/test_ext.py
Labels: C-enhancement, A-project

#2112 Remove unused audio APIs
  docs/changelog.rst
  mopidy/audio/__init__.py
  mopidy/audio/utils.py
  tests/audio/test_utils.py
Labels: A-audio
